### ISSUE TITLE
 	 	sclang-vars.el is named sclang-vars.el.in

### ISSUE THREAD

**Issue by escuta** [supercollider/scel#21]
When trying to get help working in emacs, the help library was not being loaded. I noticed that sclang-vars.el is named sclang-vars.el.in. Renaming it sclang-vars.el solved the problem for me.

**Comment by brianlheim** [comment]
you probably installed the project by copying the folder directly -- you are intended to install it via CMake, which configures `sclang-vars.el.in` to produce `sclang-vars.el`.

**Comment by Sleepful** [comment]
How to install it via CMake then? Readme doesn't explain.
