### ISSUE TITLE
Region Selection Fails in Doom Emacs

### ISSUE THREAD

**Issue by KonVas** [supercollider/scel#29]
Hi all, 

Is there any known issue about code navigation? I noticed some inconsistent behavior when trying to select regions of sc code inside my SC Workspace buffer.

I am on a 10.15 MacOS machine using 3.11 SC and Doom Emacs (28.0.50).

**Comment by novadeviator** [comment]
I think you need to be more precise. What exactly do you mean by 'selecting'? If I need to select in emacs I use C-space to start region, and C-space again to stop selecting a region. I'm not sure if this is the same in Doom Emacs. If I double click on parenthesis, it should select everthing inside parenthesis.

**Comment by KonVas** [comment]
I figured this out, now using Ctr-M x and works fine. I am closing this issue.
