### ISSUE TITLE
emacs-w3m help topics missing until accessing them via GUI help

### ISSUE THREAD

**Issue by dylangleason** [supercollider/scel#31]
## Summary

After a fresh installation of `scel`, most help topics appear to be missing when using w3m. Running `sc-index-help-topics` interactively does not appear to resolve the issue, but viewing the same help topics in the GUI does cause those help topics to subsequently appear using w3m after restarting the interpreter.

## Configuration

- **OS**: `Linux 4.19.0-8-rt-amd64 #1 SMP PREEMPT RT Debian 4.19.98-1 (2020-01-26) GNU/Linux`
- **SuperCollider version**: 3.10.0 (from the Debian repositories)
- **`scel` branch**: `master`
- **Emacs**: 27.0.91 (using `helm` and `helm-flx`)

### SuperCollider Help paths

```elisp
("/usr/local/share/SuperCollider/Help" "~/.local/share/SuperCollider/Help")
```

Note that I installed Supercollider via the Debian repositories, but not `supercollider-emacs`, since I am using an Emacs compiled from source. Not sure if this is related to the issues I am experiencing or no. Inspecting `/usr/share/SuperCollider` does reveal a `HelpSource` directory; I am guessing this is where the doc index is generated from and stored as HTML `~/.local/share/SuperCollider/Help`...

## Steps to Reproduce

1. Ensure sclang interpreter started: `sclang-start`
2. `C-c C-h` to search for "Pbind"
3. No help topic appears in helm buffer with: `[No Match]`
4.  `C-c h` to search for "Pbind"
5. Help topic appears in helm buffer and hitting enter brings up GUI window with correct help topic.
6. Repeat step 2.
7. "Pbind" now appears in helm buffer, but pressing enter results in "SCLang: no help for Pbind"
7. Try refreshing index `sc-index-help-topics`, and repeat step 2: no change.
8. Shutdown sclang interpreter with `sclang-stop`
9. Repeat step 1-2: "Pbind" shows up in helm buffer and hitting enter brings up w3m buffer with correct help topic.

**Comment by TatriX** [comment]
It seems that gui compiles files into `"~/.local/share/SuperCollider/Help"` so after reindexing they appear in `sclang-help-topic-alist`.

**Comment by Sleepful** [comment]
Having this issue too. reindexing help, but not so much. It looks like Supercollider is compiling the helpfiles into html on-demand. Meaning that the helpfiles aren't compiled to HTML until you access them via de GUI. (on MACOS)

**Comment by Sleepful** [comment]
Solved https://github.com/supercollider/supercollider/issues/5489
Run [SCDoc.renderAll](https://doc.sccode.org/Overviews/Methods.html#renderAll) on the SClang server. Then `sc-index-help-topics`. Now you got all your help files.

**Comment by dylangleason** [comment]
Verified working with `SCDoc.renderAll`. Closing.
